upload_password & admin ynh user in place of simple admin password

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -3,11 +3,20 @@
 # Retrieve arguments
 domain=$1
 path=$2
-is_public=$3
+admin_user=$3
+upload_password=$4
+is_public=$5
 
 # Check domain/path availability
 sudo yunohost app checkurl $domain$path -a jirafeau
 if [[ ! $? -eq 0 ]]; then
+    exit 1
+fi
+
+# Chack that admin user is an existing account
+sudo yunohost user list | python ../conf/user_list.py | grep "^$admin_user$"
+if [[ ! $? -eq 0 ]]; then
+    echo "Error : the chosen admin user does not exist"
     exit 1
 fi
 
@@ -20,6 +29,8 @@ sudo cp -r ../sources/* $final_path
 sed -i "s@YNH_DOMAIN@$domain@g" ../conf/config.local.php
 sed -i "s@YNH_WWW_PATH@$path@g" ../conf/config.local.php
 sed -i "s@YNH_VAR_ROOT@$var_root@g" ../conf/config.local.php
+sed -i "s@YNH_ADMIN_USER@$admin_user@g" ../conf/config.local.php
+sed -i "s@YNH_UPLOAD_PASSWORD@$upload_password@g" ../conf/config.local.php
 sudo cp ../conf/config.local.php $final_path/lib
 sudo rm $final_path/install.php
 
@@ -53,7 +64,7 @@ sudo chmod 644 $finalphpini
 
 if [ $is_public = "Yes" ];
 then
-  sudo yunohost app setting jirafeau skipped_uris -v "/" 
+  sudo yunohost app setting jirafeau unprotected_uris -v "/" 
 fi
 
 sudo service php5-fpm restart
